spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html
logging:
  level:
    sql: debug
    #org.hibernate.orm.jdbc.bind: trace